### ISSUE TITLE
Add visual banner with subscape

### ISSUE THREAD

**Issue by VladUXUI** [tahowallet/taho.xyz#179]
We need to add a more visual banner for Subscape, something more enticing that makes you want to click it.
The image can either be a gif from the video, or the video. Let me know what i should provide if anything.

## Preview
<img width="925" alt="image" src="https://github.com/tahowallet/taho.xyz/assets/80846886/b1a8777a-a896-4127-8bd3-a6d8dcbfbaca">

## Task list

- [ ] Change Taho logo to this one 
![Taho-Worldmark-Dark](https://github.com/tahowallet/taho.xyz/assets/80846886/db3c8d3b-289b-4209-b758-e622d76d8817)

- [ ] Add Subscape banner

- [ ] Remove Sign the pledge banner
